### PR TITLE
Django updates after update to 1.8.14

### PR DESCRIPTION
**Pull request by atodorov**
This is a successor of #81. The biggest change is adding the missing migrations for initial data and converting the django_comments migration to not use RawSQL. The rest are some left-overs.

### CODE REVIEW

**Comment by atodorov** [comment]
@tkdchen I think you may also close #4 after the latest changes.

**Comment by tkdchen** [comment]
#4 is closed.

**Comment by atodorov** [comment]
@tkdchen except commit f8fd52f (2nd one from this PR) I think the rest of them are still relevant. Can you review and give me feedback. I can split them in separate PRs so you can easily merge them but let me know if they are acceptable. 

I can work on the JSON commit later unless you beat me to it.

**Comment by tkdchen** [comment]
- https://github.com/Nitrate/Nitrate/pull/109/commits/427ab195ab31208f54e3ecd27ff72546948844ad can be merged.
- https://github.com/Nitrate/Nitrate/pull/109/commits/e94f02b1a5b613720161ed12ea8d0465b73b491f this is a good catch. Thanks.
- https://github.com/Nitrate/Nitrate/pull/109/commits/91f63a3112ab7606a94055d4f372e5b310917541 also works in my development environment. I tested creating and editing a plan and case, I didn't find an issue so far. Let's merge it at this moment.

Each of them above needs to be rebased on top of latest ``develop`` branch.

I think these three ones are not necessary now.

- https://github.com/Nitrate/Nitrate/pull/109/commits/340d7bbc2601c6c7b346ebfbad954c86dfcd4a3c
- https://github.com/Nitrate/Nitrate/pull/109/commits/f8fd52fcbe1cce081892e2710afad4c494169496
- https://github.com/Nitrate/Nitrate/pull/109/commits/105cda1e58c192880a0ff12e427ea9ea13bbbde1

**Comment by atodorov** [comment]
@tkdchen opened PRs #117, #118, #119 and #120 to address the commits above. 

I agree that f8fd52f and 105cda1 are not necessary at the moment (I will however compare my changes with yours to figure out the differences between the two solutions).

Why do you think 340d7bb is not necessary ? It is cleaning up some left overs. I think we can safely merge it.

**Comment by tkdchen** [comment]
> Why do you think 340d7bb is not necessary ? It is cleaning up some left overs. I think we can safely merge it.

Right. 340d7bb should not be ignored. Sorry.

**Comment by atodorov** [comment]
How do you feel about dropping Python 2.6 ? There's already an issue open for that, see #111.

Are you aware of other places in the code where we special case 2.6 vs 2.7 so I can take a look at them (and most likely delete them) or it is a matter of just saying we don't support Python 2.6 and bumping the requirements ?

**Comment by tkdchen** [comment]
A comment on f8fd52f, at this moment I find what ``groups.json`` does should be done in migration as well, that is for adding default permissions to several pre-defined groups, such as Tester and Administrator. I'm going to fix this in another patch later.

**Comment by tkdchen** [comment]
Regarding the Python 2.6 issue, currently, what need to do in my mind includes

- remove Python 2.6 environment in Travis configuration file
- say Nitrate does not support Python 2.6. Probably need to modify ``classifiers`` in ``setup.py`` and documentation somewhere.
- I can't remember any special case 2.6 vs 2.7 at this moment. Maybe no. Dropping Python 2.6 should not break anything in the code. (Hope I'm lucky :)

**Comment by atodorov** [comment]
@tkdchen ok then. I will clean up 340d7bb and deal with Python 2.6 removal in a separate PR. Closing this one.

**Pull request closed without merging**
