### PR TITLE
Change data

### PR DESCRIPTION
**Pull request by tkdchen**
Remove an unnecessary initial data file for profiles app.

Replace ``Administrators`` and ``Testers`` with ``Administrator`` and ``Tester``.

### CODE REVIEW

**Comment by atodorov** [comment]
Looks good but let me test the migrations more thoroughly before merging.

**Comment by atodorov** [comment]
:+1:  looks good to me

**Comment by atodorov** [comment]
Btw there is ./tcms/core/fixtures/groups.json still left in the repository. Maybe you want to remove it together with this PR ?

**Comment by tkdchen** [comment]
I'll remove ``./tcms/core/fixtures/groups.json`` later. That is related to the issue of adding default permissions to each default group.

**Pull request merged**
