### PR TITLE
Fix quotes in sqls.py

### PR DESCRIPTION
**Pull request by mihailgmihaylov**

### CODE REVIEW

**Comment by atodorov** [comment]
@tkdchen this happens when we use PostgreSQL database (I know it isn't supported but still).

Steps to reproduce the problem:

1) Create Test Run with only 1 Test Case inside
2) When the Test Run is opened then click Cases -> Add menu (from the blue java script button)

Expected results:

Form to select which Test Cases to add

Actual results:

500 error


Additional info:
Removing the quotes makes Postgres happy. You will also see that none of the other queries in this file have quotes. I will work on another PR to refactor these queries and use ORM instead but that is a quick fix.

**Comment by tkdchen** [comment]
Thanks for making this change. I'm glad to see step forward to make Nitrate workable with PostgreSQL. Regarding the SQLs, all of them, in each ``sqls.py``, they actually came from original lines of ORM code for fixing many performance issues. To make part of them run in PostgreSQL, I prefer to make changes to the SQL statement directly rather than converting back to lines of ORM code.

**Comment by atodorov** [comment]
@tkdchen I understand the performance concerns surrounding the SQL statements and the report app in particular but using raw SQL is not the way to go. It is against Django principles to use SQL, probably defeats some of their built in SQL-injection protections, isn't portable between various DB backends and most importantly will break the moment you rename some of the tables.

If performance is of the essence then we should take special care (and possibly provide tests) when constructing the Django ORM queries. I know for complex queries it may not be straight forward but  IMO this is usually worth the investment. 

Anyway, the whole SQL vs. ORM is for another issue/PR.

**Comment by tkdchen** [comment]
@mihailgmihaylov  From this moment, please sign-off your commit.

**Comment by tkdchen** [comment]
Merged.

**Comment by atodorov** [comment]
Can you close it?

**Pull request closed without merging**
