### PR TITLE
Drop support for legacy Python 2.7

### LINKED ISSUE #400: Drop Python 2.7
Then, Nitrate will be Python 3 only.

AC:

- Python 2.7 is removed from `tox.ini`
- Python 2.7 is removed from `.travis.yml`
- Remove `if sys.version_info.major < 3:` from `setup.py`

### PR DESCRIPTION
**Pull request by hugovk**
Fixes #400.

### CODE REVIEW

**Comment by atodorov** [comment]
@hugovk you can also try https://github.com/kiwitcms/Kiwi/ which is 3.6 only!

**Comment by tkdchen** [comment]
@hugovk  Nice! Thank you very much. I've started to look at your PR and will commet out if there is.

**Comment by tkdchen** [comment]
I have read through the changes and tested locally. No problem is found so far. :+1: 

Just one comment, could you please sign-off your commits? Nitrate uses `Developer Certificate of Origin` mentioned here https://nitrate.readthedocs.io/en/latest/contribution.html#sign-off-commit. After you are done to sign-off commits, this PR is good to be merged.

**Comment by hugovk** [comment]
Updated!

**Comment by tkdchen** [comment]
@hugovk 

The last signed-off commit seems be the original commit "the future is now" and other commits are still not signed-off yet. Were you going to squash all commits into one? Can you please double-check?

**Comment by hugovk** [comment]
I think I messed up the Git commands, I ran `git commit --amend -s -c c1a4caf945cc1fc6ad0eace1d7b878ef04b8175a` for each one, but clearly that didn't work.

What do you recommend?

**Comment by tkdchen** [comment]
``--amend`` should just modify the top commit. You could probably try ``git rebase --signoff f0e8ddb54ce28c14e1d2cf9fcf34cc58888c6fb6``, if your local branch is based on the latest develop branch.

**Comment by hugovk** [comment]
Thank you, updated!

**Comment by tkdchen** [comment]
@hugovk  Cool. 53a3ccd has duplicate subject 0a12a8f has. Would you please fix this? I think the original commit message subject is still a good choice.

**Comment by hugovk** [comment]
Thanks, fixed!

**Comment by tkdchen** [comment]
Nice! Thank you very much. :tada:

**Comment by hugovk** [comment]
You're welcome!

**Pull request merged**
