### PR TITLE
fix testplans unittests and all pass

### PR DESCRIPTION
**Pull request by tkdchen**
Following two issues are also fixed
- add missing XML version setting
- fix error testcase creation when importing from XML document exported
  previously

### CODE REVIEW

**Comment by atodorov** [comment]
What is the status of this PR ?

**Comment by tkdchen** [comment]
Related to #113

**Comment by tkdchen** [comment]
> What is the status of this PR ?

@atodorov I'll rebase this later.

**Comment by tkdchen** [comment]
Tested this patch by ``TEST_TARGET=tcms.testplans make test``

**Comment by tkdchen** [comment]
Rebased.

**Comment by atodorov** [comment]
@tkdchen what is the purpose of this PR? In the travis logs I see less test cases being executed compared to the develop branch. Also the XML fixture appears to be the opposite of migrations and FactoryBoy.

Maybe you need to pick this apart into smaller chunks ?

**Comment by tkdchen** [comment]
@atodorov ``tcms/fixtures/cases-to-import.xml`` is for testing the "Import cases". This patch aims to make ``testplans/tests.py`` be able to run based on the latest changes to the codebase recently. For example, for running each test, a fresh test plan is created instead of using an existent one loaded from a ``initial_data`` file.

``--exclude`` is added for running ``testplans/tests.py``. So, if you run other apps' tests, I guess Makefile should be modified properly to ignore something like ``TestRun``, ``TestCaseRun``, etc. So far, I have no idea how to use ``exclude`` option in ``setup.cfg``.

**Pull request merged**
