### PR TITLE
Refactor SQL and use ORM queries instead

### PR DESCRIPTION
**Pull request by atodorov**
Supersedes #135 by removing all hard-coded SQL statements and replacing them with Django ORM queries. I have split changes into separate commits for easier reviewing but can squash them into one bigger commit before merging if you like. 

In this particular instance the ORM queries result in the same SQL statements being sent to the DB backend so there should be no change in performance constraints. There is even a slight improvement at a couple of places where I've gotten rid of secondary hits to DB or fetching duplicate rows when they were not needed.

@tkdchen please review and let me know if you want me to squash all commits together.

### CODE REVIEW

**Comment by atodorov** [comment]
ping. any update here ?

**Comment by tkdchen** [comment]
Sorry, so far, it is not necessary to convert these SQL queries back to ORM. It is not time to merge these patches now.

**Comment by atodorov** [comment]
OK, I understand it is not priority to do this change right now, but the patch looks good and doesn't actually change the underlying queries. It doesn't bring any negative impact but on the other hand makes Nitrate more portable. I don't understand why not simply merge.

**Comment by tkdchen** [comment]
I'll merge these commits one by one as I'm replacing ``REQUEST`` and adding tests in ``testruns`` app.

**Comment by tkdchen** [comment]
Commits except 12584d4 are merged. What 4633955 fixes are fixed in those merged commits.

Thanks.

**Pull request closed without merging**
